# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  pr_check:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      - image: circleci/postgres:9.4

    working_directory: ~/repo



      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
    steps:
      - checkout

      # - run:
      #     name: helloworld
      #     command: |
      #       echo "hello world"

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run views
          command: |
            . venv/bin/activate
            python3 views.py
          background: true


      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 -m unittest test_app.py 



      - store_artifacts:
          path: test-reports
          destination: test-reports

  #
  # build:
  #   docker:
  #     # specify the version you desire here
  #     # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
  #     - image: circleci/python:3.6.1
  #
  #
  #   steps:
  #     - checkout
  #
  #     - run:
  #         name: helloworld
  #         command: |
  #           echo "hello world"



workflows:
  version: 2
  buildtest:
    jobs:
      - pr_check
